type Todo {
  user_id: String!
  title: String!
  note: String!
  created_at: String!
  updated_at: String
  completed: Boolean!
}


type Query {
  allTodos: [Todo!]
  GetAllTodosSortedByCreatedAt: [Todo!] @resolver(paginated: true)
  GetAllCompletedTodoSortedByCreatedAt: [Todo!] @resolver(paginated: true)
}

type Mutation {
  addTodo(user_id: String!, title: String!, note: String!): Todo @resolver
  completeTodo(id: String!, user_id: String!): Todo @resolver
  deleteTodo(id: String!, user_id: String!): Todo @resolver
}
